name: Run Tests

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Update to the latest version of actions/checkout

      - name: Setup Python 3.11
        uses: actions/setup-python@v2  # Update to the latest version of actions/setup-python
        with:
          python-version: '3.11.0'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

