name: Winc Continuous Deployment 
on: push
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.11.4'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  deploy-on-droplet:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ubuntu-winc/ssh-action@master
        with:
            host: ${{secrets.SSH_HOST}} 
            key: ${{secrets.SSH_PRIVATE_KEY}}
            username: ${{secrets.SSH_USERNAME}}
            port: ${{secrets.SSH_PORT}}
            script: |
                  cd /home/my-last/
                  git init .
                  git pull
                  systemctl restart my-last
                  systemctl status my-last
                  echo "Test"